[package]
name = "vtext"
version = "0.1.0-alpha.1"
authors = ["Roman Yurchak <rth.yurchak@pm.me>"]
edition = "2018"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
panic = 'unwind'
overflow-checks = false

[dependencies]
regex = "1"
lazy_static = "1.2.0"
seahash = "3.0.6"
ndarray = "0.12.1"
sprs = "0.6.3"
unicode-segmentation = "1.2.1"
hashbrown = "0.1"
