[package]
name = "vtextpy"
version = "0.1.0-alpha.1"
authors = ["Roman Yurchak <rth.yurchak@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "~0.12.0"
sprs = "0.6.2"
vtext = {"path" = "../"}
rust-stemmers = "1.1.0"

[dependencies.numpy]
version = "0.4.1"
features = ["python3"]

[dependencies.pyo3]
version = "0.5.2"
features = ["extension-module"]
