[package]
name = "text-vectorize-py-wrapper"
version = "0.1.0-alpha.1"
authors = ["Roman Yurchak <rth.yurchak@pm.me>"]

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.12"

[dependencies.numpy]
version = "0.4.0-alpha.1"
git = "https://github.com/rust-numpy/rust-numpy"
features = ["python3"]

[dependencies.pyo3]
version = "= 0.5.0"
features = ["extension-module"]
